In [46]:
def Doolittle(macierz,n):
    
    U = [[0.0]*n for x in range(n)]
    L = [[0.0]*n for x in range(n)]

    for i in range(0,n):
        for k in range(i, n):
            suma = sum([L[i][j] * U[j][k] for j in range(i)])
            U[i][k] = macierz[i][k] - suma
        for k in range(i, n):
            if i == k:
                L[i][i] = 1
                continue
            suma = sum([L[k][j] * U[j][i] for j in range(i)])
            L[k][i] = (macierz[k][i] - suma) / U[i][i]
    return [L,U]

In [47]:
def Crout(macierz,n):
   
    U = [[0] * n for i in range(n)]
    L = [[0] * n for i in range(n)]

    for j in range(n):
        U[j][j] = 1           
        for i in range(j, n): 
            alpha = float(macierz[i][j])
            for k in range(j):
                alpha -= L[i][k]*U[k][j]
            L[i][j] = alpha
        for i in range(j+1, n):
            tempU = float(macierz[j][i])
            for k in range(j):
                tempU -= L[j][k]*U[k][i]
            if int(L[j][j]) == 0:
                L[j][j] = e-40
            U[j][i] = tempU/L[j][j]

    return [L,U]

In [48]:
def forward_D(L_D,B,n,y):
    suma = 0.0
    for i in range(n):
        for j in range(0,n):
            if i <0:
                suma = 0.0
            else:
                suma += (L_D[i][j] * pd.to_numeric(y[j]))
        y[i] = (B[i] - suma) / L_D[i][i] 
        suma = 0.0
    return y

In [49]:
def backward_D(final_y_D,x,n,U_D):
    suma = 0.0
    for i in reversed(range(n)):
        for j in range(0,n):
            if i == n-1:
                suma = 0.0
            else:
                suma += (U_D[i][j] * pd.to_numeric(x[j]))
        x[i] = (pd.to_numeric(final_y_D[i]) - suma) / U_D[i][i]
        suma = 0.0
    return x       

In [50]:
def forward_C(L_C,B,n,y1):
    suma = 0.0
    for j in range(n):
        for i in range(0,n):
            if i <0:
                suma = 0.0
            else:
                suma += (L_C[j][i] * pd.to_numeric(y1[i]))
        y1[j] = (B[j] - suma) / L_C[j][j] 
        suma = 0.0
    return y1

In [51]:
def backward_C(final_y_C,x1,n,U_C):
    suma = 0.0
    for i in reversed(range(n)):
        for j in range(0,n):
            if i == n-1:
                suma = 0.0
            else:
                suma += (U_C[j][i] * pd.to_numeric(x1[i]))
        x1[j] = (pd.to_numeric(final_y_C[j]) - suma) / U_C[j][j]
        suma = 0.0
    return x 

In [52]:
import numpy as np
import pandas as pd
import copy

# Ax = B, gdzie B to macierz wyrazów wolnych
# LUx = B
# ly = B, gdzie y = Ux

n = int(input('Podaj liczbę równań: '))
lists = [[] for _ in range(n)]
B = [[] for _ in range(n)]
y = np.array([[0.0] for i in range(n)])
x = np.array([[0.0] for i in range(n)])
y1 = np.array([[0.0] for i in range(n)])
x1 = np.array([[0.0] for i in range(n)])


for j in range(n):
    for i in range(n):
        a = input(f'Podaj wartość przy x dla x^{i+1} dla równania nr {j+1}: ')
        lists[j].append(int(a))
    c = input(f'Podaj wyraz wolny dla równania nr {j+1}: ')
    B[j].append(int(c))
    print('\n')
    
    
A = np.array(lists) 
L_D = np.array(Doolittle(lists,n)[0])
U_D = np.array(Doolittle(lists,n)[1])
L_C = np.array(Crout(lists,n)[0])
U_C = np.array(Crout(lists,n)[1])

Podaj liczbę równań: 3
Podaj wartość przy x dla x^1 dla równania nr 1: 5
Podaj wartość przy x dla x^2 dla równania nr 1: 3
Podaj wartość przy x dla x^3 dla równania nr 1: 2
Podaj wyraz wolny dla równania nr 1: 4


Podaj wartość przy x dla x^1 dla równania nr 2: 1
Podaj wartość przy x dla x^2 dla równania nr 2: 2
Podaj wartość przy x dla x^3 dla równania nr 2: 0
Podaj wyraz wolny dla równania nr 2: 6


Podaj wartość przy x dla x^1 dla równania nr 3: 3
Podaj wartość przy x dla x^2 dla równania nr 3: 0
Podaj wartość przy x dla x^3 dla równania nr 3: 4
Podaj wyraz wolny dla równania nr 3: 3




In [53]:
print('---------DOOLITTLE---------' )
print('A:','\n',A,'\n')
print('L:','\n',L_D,'\n')
print('U:','\n',U_D)
print('\n\n')

print('---------CROUT---------' )
print('A:','\n',np.array(lists),'\n')
print('L:','\n',L_C,'\n')
print('U:','\n',U_C,'\n')

print('-----------------','\n')
final_y_D = copy.deepcopy(forward_D(L_D,B,n,y))
final_x_D = backward_D(final_y_D,x,n,U_D)
final_y_C = copy.deepcopy(forward_C(L_C,B,n,y1))
final_x_C = copy.deepcopy(backward_C(final_y_C,x1,n,U_C))

print('Rozkład A = L * U, algorytm Doolittle''a.')
print('Dla równania A * x = B, wartości x są następujące:','\n')
for i in range(len(final_x_D)):
    print(f'x{i+1} = ',",".join(repr(e) for e in final_x_D[i]))
print('\n')
print('-----------------','\n')
print('Rozkład A = L * U, algorytm Crout''e.')
print('Dla równania A * x = B, wartości x są następujące:','\n')
for i in range(len(final_x_C)):
    print(f'x{i+1} = ',",".join(repr(e) for e in final_x_C[i]))

---------DOOLITTLE---------
A: 
 [[5 3 2]
 [1 2 0]
 [3 0 4]] 

L: 
 [[ 1.          0.          0.        ]
 [ 0.2         1.          0.        ]
 [ 0.6        -1.28571429  1.        ]] 

U: 
 [[ 5.          3.          2.        ]
 [ 0.          1.4        -0.4       ]
 [ 0.          0.          2.28571429]]



---------CROUT---------
A: 
 [[5 3 2]
 [1 2 0]
 [3 0 4]] 

L: 
 [[ 5.          0.          0.        ]
 [ 1.          1.4         0.        ]
 [ 3.         -1.8         2.28571429]] 

U: 
 [[ 1.          0.6         0.4       ]
 [ 0.          1.         -0.28571429]
 [ 0.          0.          1.        ]] 

----------------- 

Rozkład A = L * U, algorytm Doolittlea.
Dla równania A * x = B, wartości x są następujące: 

x1 =  -3.25
x2 =  4.625
x3 =  3.1874999999999996


----------------- 

Rozkład A = L * U, algorytm Croute.
Dla równania A * x = B, wartości x są następujące: 

x1 =  -3.25
x2 =  4.625
x3 =  3.1874999999999996


In [54]:
final_y_C

array([[0.8       ],
       [3.71428571],
       [3.1875    ]])

In [55]:
final_y_D

array([[4.        ],
       [5.2       ],
       [7.28571429]])